language: python

matrix:
  include:
    - name: "python 3.7 on xenial Linux"
      python: 3.7
      dist: xenial
      sudo: true
    - name: "python 3.8 on xenial Linux"
      python: 3.8
      dist: xenial
      sudo: true
#    - name: "Python 3.7.2 on macOS"
#      os: osx
#      osx_image: xcode10.2
#      language: shell
#    - name: "Python 3.7.3 on Windows"
#      os: windows
#      language: shell
#      before_install: choco install python3
#      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install .
  - pip3 install coveralls
  - pip3 install nose

# command to run tests
script:
  - python3 -m nose --with-doctest --with-coverage -c nose.cfg || python -m nose --with-doctest --with-coverage -c nose.cfg

after_success:
- coveralls

